### ISSUE TITLE
How to find functions loaded at runtime through RegisterNatives

### ISSUE THREAD

**Issue by H0r53** [Ayrx/ghidra_utils#13]
At the end of your [article](https://www.ayrx.me/ghidra-jnianalyzer/), you mentioned:

> As the script assumes that all JNI functions have names that begin with Java_, it will miss functions that are loaded at runtime through RegisterNatives unless you first rename those functions to fit the expected naming convention.

I am using the plugin in Ghidra (very nice by the way), and I've already imported the JNI data types from `jni_all.gdt`.

Unfortunately, `JNIAnalyzer` does not find anything in the APK Shared Object lib I'm reversing. When I run `nm --dynamic` on the shared object I only see `T JNI_OnLoad`. This binary has clearly been stripped, and is using obfuscation to thwart reversing.

My question is - How can I go about identifying the Native JNI functions in the shared object that correlate to the native functions I've identified in the APK? These functions clearly do not start with `Java_`, so the linker must be finding them somehow.

Thank you

**Comment by Ayrx** [comment]
Identify calls to `RegisterNatives` either with static analysis or dynamically through binary instrumentation.

The third parameter to `RegisterNatives` is an array of structures identifying the methods of a class, which contains a `fnPtr` field pointing to the native function.

```
jint RegisterNatives(JNIEnv *env, jclass clazz, const JNINativeMethod *methods, jint nMethods);
```
