### ISSUE TITLE
incompatible with ghidra

### ISSUE THREAD

**Issue by linhlhq** [Ayrx/ghidra_utils#7]
Hello, when I built the plugin and installed I got this error. How do I fix it? Thanks.
![Screen Shot 2019-11-08 at 12 00 36 PM](https://user-images.githubusercontent.com/28854132/68451077-ee17cb80-021f-11ea-85bd-f5f92608f7c1.png)

**Comment by Ayrx** [comment]
Hi!

I believe it's because I have `extension.properties` set to 9.0.4 here: https://github.com/Ayrx/JNIAnalyzer/blob/master/JNIAnalyzer/extension.properties#L4

You can try changing that and recompiling to see if it works for you. I'll bump up the version when I have time to move to 9.1 and test.

**Comment by Ayrx** [comment]
Fixed in 51d45e2. It should work in Ghidra 9.1 now.
